trigger:
  batch: true
  branches:
    include:
      - main

pr:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: bestrong-secrets

jobs:
  - job:
    displayName: Terraform deployment
    steps:
      - checkout: self
        displayName: Repository checkout
      
      - task: TerraformInstaller@1
        displayName: Install Terraform
        inputs:
          terraformVersion: 1.7.5

      - task: TerraformTaskV4@4
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: "bestrong-wif-connect"
          backendAzureRmResourceGroupName: $(bestrong-backend-rg)
          backendAzureRmStorageAccountName: $(betsrong-backend-sa)
          backendAzureRmContainerName: $(bestrong-backend-container)
          backendAzureRmKey: $(bestrong-backend-key)
        
      - task: TerraformTaskV4@4
        displayName: Terraform validate
        inputs:
          provider: 'azurerm'
          command: 'validate'
          environmentServiceNameAzureRM: 'bestrong-wif-connect'

      - task: TerraformTaskV4@4
        displayName: Terraform plan
        condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'bestrong-wif-connect'
          commandOptions: '-var="mssql-admin-username=$MSSQL-ADMIN-USERNAME" -var="mssql-admin-password=$(mssql-admin-password)" -var="bestrong-client-id=$(arm_client_id)" -var="bestrong-client-secret=$(arm_client_secret)" -var="bestrong-tenant-id=$(arm_tenant_id)" -var="bestrong-subscription-id=$(arm_subscription_id)"'

      - task: TerraformTaskV4@4
        displayName: Terraform apply
        condition: or(eq(variables['Build.Reason'], 'BatchedCI'), eq(variables['Build.Reason'], 'IndividualCI'))
        inputs:
          provider: 'azurerm'
          command: 'apply'
          environmentServiceNameAzureRM: 'bestrong-wif-connect'
          commandOptions: '-var="mssql-admin-username=$MSSQL-ADMIN-USERNAME" -var="mssql-admin-password=$(mssql-admin-password)" -var="bestrong-client-id=$(arm_client_id)" -var="bestrong-client-secret=$(arm_client_secret)" -var="bestrong-tenant-id=$(arm_tenant_id)" -var="bestrong-subscription-id=$(arm_subscription_id)"'
