trigger:
  batch: true
  branches:
    include:
      - main

pool:
  name: Self-Hosted

variables:
  - group: bestrong-secrets

jobs:
  - job:
    displayName: Terraform deployment
    steps:
      - checkout: self
        displayName: Repository checkout

      - script: echo "Hello, $(mssql-admin-username)!"
        displayName: 'Run a one-line script'