trigger:
  batch: true
  branches:
    include:
      - main

pool:
  name: Self-Hosted
  demands: 
  - Terraform
  - AzCLI

variables:
  - group: bestrong-secrets

jobs:
  - job:
    displayName: Terraform deployment
    steps:
      - checkout: self
        displayName: Repository checkout

      - script: |
          echo $(mssql-admin-username)
          az login --service-principal -u $(bestrong-cliend-id) -p $(bestrong-client-secret) -t $(bestrong-tenant-id)
          terraform init
          
        displayName: 'Run a one-line script'