trigger:
  batch: true
  branches:
    include:
      - main

pool:
  name: Self-Hosted
  demands: Terraform

variables:
  - group: bestrong-secrets

jobs:
  - job:
    displayName: Terraform deployment
    steps:
      - checkout: self
        displayName: Repository checkout

      - script: |
          ls
          pwd
          terraform init
          echo $MYSQL_USER
        displayName: 'Run a one-line script'
        env:
          MYSQL_USER: $(mssql-admin-username)