trigger:
  batch: true
  branches:
    include:
      - main

pool:
  name: Self-Hosted
  demands: 
  - Terraform
  - AzCLI

variables:
  - group: bestrong-secrets

jobs:
  - job:
    displayName: Terraform deployment
    steps:
      - checkout: self
        displayName: Repository checkout

      - script: |
          terraform init
          terraform validate
        displayName: 'Run a one-line script'
        env:
          ARM_CLIENT_ID: $(bestrong-cliend-id)
          ARM_CLIENT_SECRET: $(bestrong-client-secret)
          ARM_TENANT_ID: $(bestrong-tenant-id)
          ARM_SUBSCRIPTION_ID: $(bestrong-subscription-id)