trigger: none

pr:
  - main

pool:
  name: Self-Hosted
  demands: 
  - Terraform
  - AzCLI

variables:
  - group: bestrong-secrets

jobs:
  - job:
    displayName: Terraform validation
    steps:
      - checkout: self
        displayName: Repository checkout

      - script: |
          terraform init
          terraform validate
          terraform plan -var "mssql-admin-username=$MYSQL_ADMIN_USERNAME" -var "mssql-admin-password=$MYSQL_ADMIN_PASSWORD"
        displayName: 'Running terraform plan to test configuration'
        env:
          ARM_CLIENT_ID: $(bestrong-cliend-id)
          ARM_CLIENT_SECRET: $(bestrong-client-secret)
          ARM_TENANT_ID: $(bestrong-tenant-id)
          ARM_SUBSCRIPTION_ID: $(bestrong-subscription-id)
